// Auto-generated question bank - 110 questions
const quizData = [
  { id:1, cat:'present', q:'The sun ______ (rise) in the east.', options:['rises','is rising','has risen','rose'], ans:0, exp:'Universal truth → Present Indefinite' },
  { id:2, cat:'present', q:'Look! The baby ______ (sleep).', options:['sleeps','is sleeping','has slept','slept'], ans:1, exp:'Action going on now → Present Continuous' },
  { id:3, cat:'present', q:'She usually ______ (go) to school by bus.', options:['goes','is going','has gone','went'], ans:0, exp:'Habitual action → Present Indefinite' },
  { id:4, cat:'present', q:'Water ______ (boil) at 100°C.', options:['boils','is boiling','has boiled','boiled'], ans:0, exp:'Universal truth' },
  { id:5, cat:'present', q:'Quiet! The teacher ______ (speak).', options:['speaks','is speaking','has spoken','spoke'], ans:1, exp:'Action happening now' },
  { id:6, cat:'present', q:'I ______ (write) a letter now.', options:['write','am writing','have written','wrote'], ans:1, exp:'Present Continuous' },
  { id:7, cat:'present', q:'The train to Delhi ______ (leave) at 8 p.m. every day.', options:['leaves','is leaving','has left','left'], ans:0, exp:'Scheduled / habitual' },
  { id:8, cat:'present', q:'Honesty ______ (be) the best policy.', options:['is','is being','has been','was'], ans:0, exp:'Universal truth' },
  { id:9, cat:'present', q:'He ______ (not like) sweets.', options:['does not like','is not liking','has not liked','did not like'], ans:0, exp:'State verb – Simple Present' },
  { id:10, cat:'present', q:'Iron ______ (melt) at a high temperature.', options:['melts','is melting','has melted','melted'], ans:0, exp:'General truth' },
  { id:11, cat:'present', q:'What ______ you ______ (read) now?', options:['are / reading','do / read','have / read','did / read'], ans:0, exp:'Action at the moment' },
  { id:12, cat:'present', q:'He can\'t go now as he ______ (feel) unwell.', options:['feels','is feeling','has felt','felt'], ans:0, exp:'State verb – usually Simple Present' },
  { id:13, cat:'present', q:'The Victoria Memorial ______ (stand) in the Maidan.', options:['stands','is standing','has stood','stood'], ans:0, exp:'Permanent state / fact' },
  { id:14, cat:'present', q:'She always ______ (quarrel) with others but today she ______ (behave) nicely.', options:['quarrels / is behaving','is quarrelling / behaves','has quarrelled / behaved','quarrelled / behaved'], ans:0, exp:'Habit + temporary change' },
  { id:15, cat:'present', q:'I usually ______ (go) to office by car but today I ______ (go) by bus.', options:['go / am going','am going / go','have gone / went','went / go'], ans:0, exp:'Habit vs temporary action' },
  { id:16, cat:'present', q:'The dogs ______ (bark) all night, but today they ______ (keep) quiet.', options:['bark / are keeping','are barking / keep','have barked / kept','barked / kept'], ans:0, exp:'Habitual vs present continuous' },
  { id:17, cat:'present', q:'Will you please wait? He ______ (have) a bath now.', options:['is having','has','has had','had'], ans:0, exp:'Action in progress' },
  { id:18, cat:'present', q:'The jet ______ (fly) at 1000 kilometre per hour.', options:['flies','is flying','has flown','flew'], ans:0, exp:'General fact / capacity' },
  { id:19, cat:'present', q:'She ______ (copy) a letter. She usually ______ (do) it very quickly.', options:['is copying / does','copies / is doing','has copied / did','copied / does'], ans:0, exp:'Present Continuous + habit' },
  { id:20, cat:'present', q:'The book is about a man who ______ (fight) all odds and ______ (achieve) success.', options:['fights / achieves','is fighting / is achieving','fought / achieved','has fought / has achieved'], ans:0, exp:'Narrative / general present' },
  { id:21, cat:'present', q:'We ______ (leave) Calcutta on the 10th and ______ (hope) to reach Benaras on the 12th.', options:['leave / hope','are leaving / are hoping','have left / hoped','left / hoped'], ans:0, exp:'Future arrangement' },
  { id:22, cat:'present', q:'The boys ______ (swim) in the pool; I ______ (hear) their shouts.', options:['are swimming / hear','swim / am hearing','have swam / heard','swam / heard'], ans:0, exp:'Present Continuous + perception verb' },
  { id:23, cat:'present', q:'They ______ (try) as hard as possible to complete the job by Monday.', options:['are trying','try','have tried','tried'], ans:0, exp:'Current effort' },
  { id:24, cat:'present', q:'My examination ______ (begin) tomorrow.', options:['begins','is beginning','has begun','began'], ans:0, exp:'Fixed future (timetable)' },
  { id:25, cat:'present', q:'He ______ (work) on a new project and ______ (hope) to complete it by next week.', options:['is working / hopes','works / is hoping','has worked / hoped','worked / hoped'], ans:0, exp:'Current activity + state' },
  { id:26, cat:'perfect', q:'I ______ never ______ (see) a crocodile before.', options:['have / seen','had / seen','am / seeing','will / see'], ans:0, exp:'Experience up to now → Present Perfect' },
  { id:27, cat:'perfect', q:'It ______ (rain) since morning.', options:['has been raining','is raining','rained','had rained'], ans:0, exp:'Started earlier, still continuing' },
  { id:28, cat:'perfect', q:'They ______ (watch) TV since 6 p.m.', options:['have been watching','are watching','watched','had watched'], ans:0, exp:'Present Perfect Continuous' },
  { id:29, cat:'perfect', q:'We ______ (live) here since 1982.', options:['have lived','are living','lived','had lived'], ans:0, exp:'Period continuing to present' },
  { id:30, cat:'perfect', q:'I ______ (buy) a new bicycle recently.', options:['have bought','bought','am buying','had bought'], ans:0, exp:'Recent past with present relevance' },
  { id:31, cat:'perfect', q:'The water ______ (boil) for a long time.', options:['has been boiling','is boiling','boiled','had boiled'], ans:0, exp:'Duration continuing now' },
  { id:32, cat:'perfect', q:'I ______ (see) the boy just now.', options:['have seen','saw','am seeing','had seen'], ans:0, exp:'Just finished – Present Perfect' },
  { id:33, cat:'perfect', q:'She ______ (not visit) us since last Puja.', options:['has not visited','did not visit','is not visiting','had not visited'], ans:0, exp:'Since + Present Perfect' },
  { id:34, cat:'perfect', q:'By the time you arrive, I ______ (finish) the work.', options:['will have finished','will finish','have finished','finished'], ans:0, exp:'Future Perfect' },
  { id:35, cat:'perfect', q:'Father ______ (teach) English for thirty years and now he ______ (retire).', options:['taught / has retired','has taught / has retired','taught / retired','was teaching / retires'], ans:0, exp:'Past period + present result' },
  { id:36, cat:'perfect', q:'They ______ (wait) to see the teacher for a long time but the teacher ______ (not come) yet.', options:['have been waiting / has not come','are waiting / does not come','waited / did not come','had waited / had not come'], ans:0, exp:'Duration + result still true' },
  { id:37, cat:'perfect', q:'I ______ (ask) him to come to my place several times.', options:['have asked','asked','am asking','had asked'], ans:0, exp:'Repeated action up to now' },
  { id:38, cat:'perfect', q:'We ______ (not hear) from you for a long time.', options:['have not heard','did not hear','are not hearing','had not heard'], ans:0, exp:'Period up to present' },
  { id:39, cat:'perfect', q:'Where ______ you ______ (be)? I ______ (be) to the doctor.', options:['have / been / have been','did / be / was','are / being / am','had / been / had been'], ans:0, exp:'Present Perfect experience' },
  { id:40, cat:'perfect', q:'It ______ (rain) for three days now and all the ponds ______ (be) filled up.', options:['has been raining / have been','is raining / are','rained / were','had been raining / had been'], ans:0, exp:'Duration + result' },
  { id:41, cat:'perfect', q:'He ______ (study) in this university for two years.', options:['has been studying','is studying','studied','had studied'], ans:0, exp:'Ongoing from past to present' },
  { id:42, cat:'perfect', q:'Why ______ you ______ (knock) at my door?', options:['are / knocking','do / knock','have / knocked','did / knock'], ans:0, exp:'Action happening now' },
  { id:43, cat:'perfect', q:'I ______ (lose) my book.', options:['have lost','lost','am losing','had lost'], ans:0, exp:'Result still relevant' },
  { id:44, cat:'perfect', q:'The boys ______ (break) the glass window.', options:['have broken','broke','are breaking','had broken'], ans:0, exp:'Recent action with present result' },
  { id:45, cat:'perfect', q:'They ______ (win) the match.', options:['have won','won','are winning','had won'], ans:0, exp:'Recent result' },
  { id:46, cat:'perfect', q:'I ______ (read) the book since yesterday.', options:['have been reading','am reading','read','had read'], ans:0, exp:'Started yesterday, still continuing' },
  { id:47, cat:'perfect', q:'It ______ (rain) for a week.', options:['has been raining','is raining','rained','had rained'], ans:0, exp:'Duration continuing' },
  { id:48, cat:'perfect', q:'She ______ (send) a postcard to me.', options:['has sent','sent','is sending','had sent'], ans:0, exp:'Completed with present relevance' },
  { id:49, cat:'perfect', q:'He ______ (show) me the letter.', options:['has shown','showed','is showing','had shown'], ans:0, exp:'Present Perfect' },
  { id:50, cat:'perfect', q:'I ______ (try) for this for a long time.', options:['have been trying','am trying','tried','had tried'], ans:0, exp:'Duration up to now' },
  { id:51, cat:'past', q:'He ______ (walk) in the field when a dog ______ (come).', options:['was walking / came','walked / came','had walked / came','is walking / comes'], ans:0, exp:'Past Continuous + Simple Past' },
  { id:52, cat:'past', q:'She ______ (work) in the kitchen when I ______ (meet) her.', options:['was working / met','worked / met','had worked / met','is working / meet'], ans:0, exp:'Background action + interrupting action' },
  { id:53, cat:'past', q:'When I ______ (arrive) at the station, Ajoy ______ (wait) for me.', options:['arrived / was waiting','arrived / waited','had arrived / waited','arrive / is waiting'], ans:0, exp:'Simple Past + Past Continuous' },
  { id:54, cat:'past', q:'I ______ (see) you yesterday when you ______ (run) after the bus.', options:['saw / were running','saw / ran','had seen / ran','see / are running'], ans:0, exp:'Past Continuous for ongoing action' },
  { id:55, cat:'past', q:'The patient ______ (die) before the doctor ______ (reach).', options:['had died / reached','died / reached','has died / reaches','was dying / reached'], ans:0, exp:'Past Perfect for earlier action' },
  { id:56, cat:'past', q:'Her father ______ (leave) before she ______ (come).', options:['had left / came','left / came','has left / comes','was leaving / came'], ans:0, exp:'Past Perfect + Simple Past' },
  { id:57, cat:'past', q:'After the principal ______ (leave), the students ______ (begin) to shout.', options:['had left / began','left / began','has left / begin','was leaving / began'], ans:0, exp:'Past Perfect after after' },
  { id:58, cat:'past', q:'I ______ (see) him a week ago.', options:['saw','have seen','had seen','was seeing'], ans:0, exp:'Finished past time → Simple Past' },
  { id:59, cat:'past', q:'He ______ (go) to school yesterday.', options:['went','has gone','had gone','was going'], ans:0, exp:'Specific past time' },
  { id:60, cat:'past', q:'Einstein ______ (discover) the Theory of Relativity.', options:['discovered','has discovered','had discovered','was discovering'], ans:0, exp:'Historical fact – Simple Past' },
  { id:61, cat:'past', q:'While they ______ (dance), we ______ (sing).', options:['were dancing / were singing','danced / sang','had danced / sang','are dancing / sing'], ans:0, exp:'Two simultaneous past actions' },
  { id:62, cat:'past', q:'We ______ (live) in this locality for fifteen years before they ______ (come).', options:['had lived / came','lived / came','have lived / come','were living / came'], ans:0, exp:'Past Perfect for earlier duration' },
  { id:63, cat:'past', q:'I ______ (tell) her that I ______ (see) her before.', options:['told / had seen','told / saw','have told / have seen','tell / saw'], ans:0, exp:'Reported past + earlier past' },
  { id:64, cat:'past', q:'As I ______ (cross) the road, I ______ (see) him and ______ (ask) him where he ______ (go).', options:['was crossing / saw / asked / was going','crossed / saw / asked / went','had crossed / had seen / asked / had gone','cross / see / ask / goes'], ans:0, exp:'Past Continuous background + Simple Past' },
  { id:65, cat:'past', q:'It ______ (rain) heavily when he ______ (knock) at the door and ______ (enter) the room.', options:['was raining / knocked / entered','rained / knocked / entered','had rained / had knocked / entered','is raining / knocks / enters'], ans:0, exp:'Past Continuous + Simple Past' },
  { id:66, cat:'past', q:'When I ______ (look) through the window, I ______ (watch) a man standing under the tree.', options:['looked / watched','was looking / was watching','had looked / had watched','look / watch'], ans:0, exp:'Simple Past sequence' },
  { id:67, cat:'past', q:'The boys ______ (play) in the garden when the tree ______ (fall) down.', options:['were playing / fell','played / fell','had played / had fallen','are playing / falls'], ans:0, exp:'Past Continuous interrupted by Simple Past' },
  { id:68, cat:'past', q:'He never ______ (want) to know who she ______ (be) or where she ______ (come) from.', options:['wanted / was / came','wants / is / comes','has wanted / has been / has come','was wanting / was / was coming'], ans:0, exp:'Simple Past narrative' },
  { id:69, cat:'past', q:'I ______ (feel) sorry when I ______ (hear) that they ______ (suffer) badly.', options:['felt / heard / were suffering','feel / hear / suffer','have felt / have heard / have suffered','was feeling / was hearing / suffered'], ans:0, exp:'Simple Past + Past Continuous' },
  { id:70, cat:'past', q:'I at last ______ (realise) that I ______ (move) in the wrong direction.', options:['realised / was moving','realise / am moving','have realised / have moved','had realised / had moved'], ans:0, exp:'Simple Past + Past Continuous' },
  { id:71, cat:'past', q:'The loudspeaker ______ (make) so much noise that we could not hear what he ______ (say).', options:['was making / was saying','made / said','has made / has said','is making / is saying'], ans:0, exp:'Past Continuous for simultaneous actions' },
  { id:72, cat:'past', q:'I ______ (go) to his house and ______ (find) that he still ______ (work) on the painting.', options:['went / found / was working','go / find / is working','have gone / have found / has worked','had gone / had found / had been working'], ans:0, exp:'Simple Past + Past Continuous' },
  { id:73, cat:'past', q:'Mr. Ray ______ (carry) a heavy bag and ______ (feel) tired.', options:['was carrying / was feeling','carried / felt','has carried / has felt','carries / feels'], ans:0, exp:'Past Continuous for ongoing state' },
  { id:74, cat:'past', q:'She ______ (play) the violin inside the room when we ______ (open) the door.', options:['was playing / opened','played / opened','had played / had opened','is playing / open'], ans:0, exp:'Past Continuous interrupted' },
  { id:75, cat:'past', q:'You ______ (go) before I ______ (come).', options:['had gone / came','went / came','have gone / come','go / come'], ans:0, exp:'Past Perfect before Simple Past' },
  { id:76, cat:'confusing', q:'He ______ it here safely. (put)', options:['laid','lay','lied','lain'], ans:0, exp:'Lay (put) → laid' },
  { id:77, cat:'confusing', q:'Do not ______ on the grass. (rest)', options:['lie','lay','laid','lain'], ans:0, exp:'Lie (rest) → base form' },
  { id:78, cat:'confusing', q:'He has ______ to his father. (speak falsely)', options:['lied','laid','lain','lay'], ans:0, exp:'Lie (false) → lied' },
  { id:79, cat:'confusing', q:'It has ______ there for a long time. (rest)', options:['lain','laid','lied','lay'], ans:0, exp:'Lie (rest) → lain' },
  { id:80, cat:'confusing', q:'The hen has ______ several eggs.', options:['laid','lain','lied','lay'], ans:0, exp:'Lay (put/produce) → laid' },
  { id:81, cat:'confusing', q:'The murderer was ______ to death.', options:['hanged','hung','hang','hanging'], ans:0, exp:'Hang (execute) → hanged' },
  { id:82, cat:'confusing', q:'He ______ the coat on the peg.', options:['hung','hanged','hang','hanging'], ans:0, exp:'Hang (suspend) → hung' },
  { id:83, cat:'confusing', q:'The birds have ______ away.', options:['flown','fled','flowed','flew'], ans:0, exp:'Fly → flown' },
  { id:84, cat:'confusing', q:'The river over ______ the banks.', options:['flowed','flown','fled','flew'], ans:0, exp:'Flow → flowed' },
  { id:85, cat:'confusing', q:'The enemy has ______ away.', options:['fled','flown','flowed','flew'], ans:0, exp:'Flee → fled' },
  { id:86, cat:'confusing', q:'He was ______ of poor parents.', options:['born','borne','bore','bear'], ans:0, exp:'Bear (birth) → born' },
  { id:87, cat:'confusing', q:'She has ______ two sons.', options:['borne','born','bore','bear'], ans:0, exp:'Bear (give birth) → borne' },
  { id:88, cat:'confusing', q:'He has ______ the burden.', options:['borne','born','bore','bear'], ans:0, exp:'Bear (carry) → borne' },
  { id:89, cat:'confusing', q:'He ______ me yesterday. (hit)', options:['struck','stroked','strike','stricken'], ans:0, exp:'Strike → struck' },
  { id:90, cat:'confusing', q:'The girl ______ her favourite cat on the back.', options:['stroked','struck','strike','stricken'], ans:0, exp:'Stroke (caress) → stroked' },
  { id:91, cat:'confusing', q:'The people were awe-______.', options:['struck','stroked','stricken','stroke'], ans:0, exp:'awe-struck' },
  { id:92, cat:'confusing', q:'The famine-______ people suffered terribly.', options:['stricken','struck','stroked','stroke'], ans:0, exp:'famine-stricken' },
  { id:93, cat:'confusing', q:'He ______ to the shore. (swim – past)', options:['swam','swum','swim','swimming'], ans:0, exp:'Swim → swam (past)' },
  { id:94, cat:'confusing', q:'He has ______ across the river.', options:['swum','swam','swim','swimming'], ans:0, exp:'Swim → swum (p.p.)' },
  { id:95, cat:'confusing', q:'The ship is ______ for England.', options:['bound','bind','bounded','binding'], ans:0, exp:'bound = headed for' },
  { id:96, cat:'confusing', q:'It is my ______ duty.', options:['bounden','bound','bind','binding'], ans:0, exp:'bounden duty' },
  { id:97, cat:'confusing', q:'He ______ the whole cup. (drink – past)', options:['drank','drunk','drink','drinking'], ans:0, exp:'Drink → drank' },
  { id:98, cat:'confusing', q:'He has ______ the whole cup.', options:['drunk','drank','drink','drinking'], ans:0, exp:'Drink → drunk (p.p.)' },
  { id:99, cat:'confusing', q:'He is dead ______. (intoxicated)', options:['drunk','drunken','drank','drink'], ans:0, exp:'dead drunk' },
  { id:100, cat:'confusing', q:'The ______ man fell into the ditch.', options:['drunken','drunk','drank','drink'], ans:0, exp:'drunken as adjective' },
  { id:101, cat:'confusing', q:'He ______ the foundation of the building.', options:['has laid','has lain','has lied','lay'], ans:0, exp:'Lay (put) → has laid' },
  { id:102, cat:'confusing', q:'As he was tired he ______ down to rest.', options:['lay','laid','lied','lain'], ans:0, exp:'Lie (rest) past → lay' },
  { id:103, cat:'confusing', q:'He ______ the watch on the table.', options:['laid','lay','lied','lain'], ans:0, exp:'Lay (put) past → laid' },
  { id:104, cat:'confusing', q:'I ______ the picture on the wall.', options:['hung','hanged','hang','hanging'], ans:0, exp:'Hang (suspend) → hung' },
  { id:105, cat:'confusing', q:'He was ______ from the gallows.', options:['hanged','hung','hang','hanging'], ans:0, exp:'Hang (execute) → hanged' },
  { id:106, cat:'confusing', q:'He ______ into a rage.', options:['flew','fled','flowed','flown'], ans:0, exp:'Fly into a rage (idiom)' },
  { id:107, cat:'confusing', q:'They refused to ______.', options:['flee','fly','flow','flown'], ans:0, exp:'Flee = escape' },
  { id:108, cat:'confusing', q:'The thief ______ away.', options:['fled','flew','flowed','flown'], ans:0, exp:'Flee past → fled' },
  { id:109, cat:'confusing', q:'Who ______ the dispensary? (establish)', options:['founded','found','find','founded'], ans:0, exp:'Found (establish) → founded' },
  { id:110, cat:'confusing', q:'It is ______ on truth.', options:['founded','found','find','founded'], ans:0, exp:'Founded on = based on' }
];
